server:
  port: 8885
spring:
  application:
    name: central-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MauricioZapata00/230802-spring-cloud-config-server
